### ISSUE TITLE
Support older `sass` versions in embedded sass

### ISSUE THREAD

**Issue by gkatsanos** [sass/embedded-host-node#147]
We're stuck to 1.32.x of `sass` because of some legacy libraries requiring old syntax. We noticed that embedded-sass starts from 1.49.x , would there be any chance to have the old versions there?

**Comment by nex3** [comment]
No, this is not planned. We strongly discourage users from pinning old Sass versions—they are totally unmaintained, so not only will you not have access to features like the embedded host, you won't get bug fixes, support for new CSS features, or security patches in the unlikely case that those become necessary.

There have been no major breaking changes between 1.32.x and the current release of Dart Sass. If you're dragging your feet on upgrading because of deprecation warnings around `/`-as-division, be aware that you can disable these in libraries by passing [`quietDeps`](https://sass-lang.com/documentation/js-api/interfaces/Options#quietDeps).
