### ISSUE TITLE
Allow using a custom sass binary

### ISSUE THREAD

**Issue by Znert** [sass/embedded-host-node#334]
I recently wanted to bootstrap a new Sveltekit app and use `sass-embedded` so that I can use SCSS in my web app. But because I run NixOS, I can't use the pre-compiled version of sass-dart you are shipping with the `sass-embedded-linux-x64` package - dynamic linking works a little differently on NixOS than on normal Linux distributions.

Now, NixOS already provides a working binary via the [dart-sass](https://mynixos.com/nixpkgs/package/dart-sass) package. However, there is no way for me to instruct `sass-embedded` to use the existing (globally installed) `sass` binary instead of the one inside the `node_modules` folder.

My idea would be to use some env variable, something like `SASS_EMBEDDED_BIN_PATH`, that I can set in order to point towards the binary I want to use.

I'm not sure if you need/want to add some checks to ensure that the `sass-embedded` package is compatible with the `sass` binary, but I think it's fair to tell the user "you are on your own if you do this".

**Comment by ntkme** [comment]
You are on your own. sass-embedded is only guaranteed to work with version matched dart-sass, and the version shipped by Nix is usually not the right version. For example, the current version in Nix is a few releases behind, and there was a breaking change for color-4 embedded protocol, which will break if you try to force older version of dart-sass from Nix.

**Comment by Znert** [comment]
Well, anything is better than not being able to run the sass compiler at all, right?

I tried to apply an `pnpm patch` to test my theory out and so far it seems to work fine. But I've only got a very basic project, so I assume there will be dragons later down the line. Will post my code for anyone running into a similar issue tomorrow, because I've also turned off my PC for the day.

As for version missmatch, I would be fine with running an older version of the library. I'll check tomorrow which binary version you support with which package version.

**Comment by ntkme** [comment]
> anything is better than not being able to run the sass compiler at all, right?

Yes, but because this can easily break, I don’t think we want to officially support it. As you already discovered you can still patch the package locally yourself.

Another solution is to port the solution used by ruby sass-embedded: https://ntk.me/2023/06/04/invoking-ld-linux-so/ Given that we now have an elf parser that read the interpreter, it should be relatively easy to port the ruby implementation.

**Comment by Znert** [comment]
As promised, here is the patch I applied for anybody in a similar spot as me:

- Run `pnpm patch sass-embedded` (if you don't use pnpm, there is also a [patch-package](https://www.npmjs.com/package/patch-package) npm package available. But I have no experience with it)
- Go to the directory that `pnpm patch` outputs and open the file `dist/lib/src/compiler-path.js`.
- Just below the `exports.compilerCommand = (() => {` line, add this code:
   ```
    const binPath = process.env.SASS_EMBEDDED_BIN_PATH;
    if (binPath) {
        return [binPath];
    }
    ```
- Apply the patch. Again, just do what the output of `pnpm patch says`

In your project root directory, you should now have a folder called `patches` with a file called `sass-embedded.patch`. For the version of `sass-embedded` I had installed, this was the content of the file:

```patch
diff --git a/dist/lib/src/compiler-path.js b/dist/lib/src/compiler-path.js
index c274baf174a035c4b568f14e7167900cb29911481b69dcf5b46641315cc65f8b..0beebe20c20cb68248f80048de57696cb44a7b57d873de3fd4ee3eb002adfee6 100644
--- a/dist/lib/src/compiler-path.js
+++ b/dist/lib/src/compiler-path.js
@@ -24,6 +24,10 @@ function isLinuxMusl(path) {
 }
 /** The full command for the embedded compiler executable. */
 exports.compilerCommand = (() => {
+    const binPath = process.env.SASS_EMBEDDED_BIN_PATH;
+    if (binPath) {
+        return [binPath];
+    }
     const platform = process.platform === 'linux' && isLinuxMusl(process.execPath)
         ? 'linux-musl'
         : process.platform;
```

In order to set the `SASS_EMBEDDED_BIN_PATH` env variable, I'm using this `flake.nix`:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
  };

  outputs = { self, nixpkgs, ... }:
  let
    lib = nixpkgs.lib;
    system = "x86_64-linux";
    pkgs = import nixpkgs {
      inherit system;
    };
  in
  {

    devShells.${system}.default = pkgs.mkShell {
      buildInputs = with pkgs; [
        nodejs_20
        pnpm
        dart-sass
      ];
      SASS_EMBEDDED_BIN_PATH = "${pkgs.dart-sass}/bin/sass";
    };

  };
}
```

To make everything work with VSCode, I've installed the [direnv](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-direnv) extension and setup an `.envrc`:

```sh
if ! has nix_direnv_version || ! nix_direnv_version 3.0.5; then
    source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.5/direnvrc" "sha256-RuwIS+QKFj/T9M2TFXScjBsLR6V3A17YVoEW/Q6AZ1w="
fi

use flake
```

More details can be found in the [`nix.direnv` repo](https://github.com/nix-community/nix-direnv).


------

Obviously this setup won't be very stable. Any update to either the `dart-sass` Nix package or the `sass-embedded` npm package could easily break the setup. But for now it seems to work...

**Comment by nex3** [comment]
I agree with @ntkme here that we should actively avoid supporting this officially because it's so easy to get broken. I think the "correct" way to handle it would be to have NixOS build the entire Sass embedded stack and `npm link` it into your project.

**Comment by Znert** [comment]
Makes sense to me. Say I would like to do something like that, how would I go about this?

Looking at your [`prepare-optional-release.ts`](https://github.com/sass/embedded-host-node/blob/main/tool/prepare-optional-release.ts) script, you download the pre-built binaries from [sass/dart-sass](https://github.com/sass/dart-sass) and package them as npm packages. I think I could write a "post init" script to my `flake.nix`, that would replace the content of the `sass-embedded-linux-x64` (or similar) to use the binaries packaged for/by NixOS.

But I think the result would just be the same: Version mismatch hell :thinking: 

I think maybe it would just be simpler to pull [a specific version of `dart-sass`](https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=dart-sass) and the appropriate npm package version of `sass-embedded`.

Of course if you can't help me, that's also fine. As long as I have a somewhat working workspace, I'm happy :smile:

**Comment by nex3** [comment]
I'm not very familiar with NixOS, but I can help you navigate the build process of these packages. When you're building the embedded host, you can pass `--compiler-path` and `--language-path` flags to `npm run init` to have it build against a local version of Dart Sass and the Sass language repo, respectively. So my recommendation would be:

* Grab whichever tagged version of the Node.js embedded host you want
* Grab Dart Sass and Sass repo versions that match its dependencies
* Run `npm run init` with the flags above

**Comment by siggerajamae** [comment]
Hello, came across when I had the same problem. There is a solution for this called nix-ld, you can read about it here: https://nix.dev/guides/faq#how-to-run-non-nix-executables This lets you install dynamic libraries to be used like "normal" by unpackaged programs.
Adding the following to my configuration.nix has solved this issue and similar ones for me:
```nix
  # Dynamic libraries for unpackaged programs
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    glibc
    libcxx
  ];
```

**Comment by martinetd** [comment]
FWIW just removing the module apparently works around the problem? Not sure if it just falls back to js or whatever

https://github.com/NixOS/nixpkgs/pull/351966/files
```
  preBuild = ''
    # using sass-embedded fails at executing node_modules/sass-embedded-linux-x64/dart-sass/src/dart
    rm -r node_modules/sass-embedded*
  ''
```

(and I'm now doing the same for rmfakecloud, that appears to have built something and it doesn't look too wrong...)

**Comment by ValJed** [comment]
@martinetd I think it'll fallback on the JS version which is way slower..

**Comment by MatthiasvB** [comment]
I'm running into the same problem using vuepress, as described [here](https://discourse.nixos.org/t/nix-build-of-vuepress-project-is-slow-or-hangs/56521/6). 

Interestingly, building outside of a nix build env (by simply running `npm run docs:build`) works, even though it shouldn't if it's using pre-built binaries. But then it doesn't work inside the nix build env with `nix build`:

```
> nixxer-docs@0.0.1 docs:build
> vuepress-vite build src

- Initializing and preparing data
✔ Initializing and preparing data - done in 4.75s
- Compiling with vite
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn /build/docs/node_modules/sass-embedded-linux-x64/dart-sass/src/dart ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /build/docs/node_modules/sass-embedded-linux-x64/dart-sass/src/dart',
  path: '/build/docs/node_modules/sass-embedded-linux-x64/dart-sass/src/dart',
  spawnargs: [
    '/build/docs/node_modules/sass-embedded-linux-x64/dart-sass/src/sass.snapshot',
    '--embedded'
  ]
}

Node.js v20.17.0
```

Unfortunately, when I delete `sass-embedded*` from the node_modules, no fallback is used in my case and it just crashes

**Comment by ntkme** [comment]
Technically, it's a nix problem instead of a sass problem, because nix is the deliberately ignoring the standard https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html.

You can use nix's `patchelf` to patch the dart executable and it will work: https://nixos.wiki/wiki/Packaging/Binaries. There are other ways, but in general you are on your own because you choose to use a non-standard OS.

There is also a way to support nix without patch or custom binary path. It's used by the embedded-host-ruby, and can potentially get ported to embedded-host-node: https://ntk.me/2023/06/04/invoking-ld-linux-so/, but given that `node_modules` is way much more easier to patch comparing to ruby gem, I don't find a strong need.

**Comment by ntkme** [comment]
> Let’s all just use Windows, most people do, very standard, problem solved, right?

To some degree even special windows variants like PE are more consistent within windows family comparing to NixOS with in Linux family… Windows is standard enough (by its own standard) that dart officially supports all windows versions later than Windows 10, and sass-embedded just works. So, problem indeed solved? - No offend but I’m not sure how to interpret this as sarcasm.

Clearly you’re one of better skilled NixOS users who understands the way around it pretty well, but most of the NixOS users I’ve seen aren’t like you. Many users don’t even know `patchelf` and just scream around about things are broken on GitHub issues, without mentioning a single word that they are on NixOS, because they misunderstand NixOS is just another “standard” Linux that they don’t have to mention. How are project maintainers supposed to react? Some project maintainers don’t even know the existence of NixOS.

On the other hand if you look at nixpkgs, they do tons of patching and they never ask upstream project to “add an environment variable” so that they can use it as a workaround. They just figure out a way to patch anyways.

It’s completely okay to use GitHub issues as a discussion board to discuss how to patch on NixOS, other NixOS users will be appreciated. However, don’t feel offended or get frustrated that upstream won’t provide what you want, it’s just part of normal life of being NixOS users.

**Comment by nex3** [comment]
> Does this project need to ship its own dart? No, it could just fall back to the system provided dartaotruntime and then things would just run.

This would fail in very confusing ways if the system dartaotruntime is at all different from the one used to compile the application. As far as I know, Dart doesn't guarantee binary compatibility even across patch versions. You'd have to build the Sass executable as well at that point, and if you're already replacing that why not replace the bundled runtime as well?

**Comment by n0099** [comment]
In nixpkgs packages that using `sass-embedded`: https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20path%3A.nix%20sass-embedded&type=code, mostly replace [`compilerCommand`](https://github.com/sass/embedded-host-node/blob/feda063874b762bf4b889fd59dec1372d7f7387c/lib/src/compiler-path.ts#L9) with early return or literal plain array to `['dart-sass']` that looks up in `$PATH` from `nativeBuildInputs` or `['${lib.getExe dart-sass}']` to reference absolute path, or just delete node package `sass-embedded` and fallback to JS impl like https://github.com/sass/embedded-host-node/issues/334#issuecomment-2495323937

**Comment by l0b0** [comment]
Does anyone know what the override is to avoid

> fetch https://github.com/sass/dart-sass/releases/download/1.101.0/dart-sass-1.101.0-linux-x64.tar.gz

and/or

> Errno::ENOENT: No such file or directory @ rb_sysopen - /nix/store/jqna62wsgfvy8lqcc3q9w7af270lqjrl-ruby3.4-sass-embedded-1.101.0/lib/ruby/gems/3.4.0/extensions/x86_64-linux/3.4.0/sass-embedded-1.101.0/sass/cli.rb (Errno::ENOENT)

during a Nix build? There seems to be quite a few solutions floating around, but none of the ones I've seen so far work with version 1.101.0.

For context, this has been blocking updates ([1](https://gitlab.com/engmark/engmark.gitlab.io/-/jobs/16428388692#L754), [2](https://gitlab.com/engmark/engmark.gitlab.io/-/jobs/16428404693#L742), [3](https://gitlab.com/engmark/engmark.gitlab.io/-/jobs/16428413731#L744)) since May.
