### ISSUE TITLE
Why sass-embeded use more dependencies than sass library when its a wrapper.

### ISSUE THREAD

**Issue by MrBns** [sass/embedded-host-node#351]
I found myself mostly craftbased dev. I do care a lot about dependencies. I am not here to reduce depencies of `sass-embeded` project. I am creating this issue just to know why 8 dependecies **not dev-dependencies** is being used for a wrapper. 

> but where the sass package is pure JavaScript, sass-embedded is instead a JavaScript wrapper around a native Dart executable.
found this from your package description, saying it is a wrapper of dart sass executive. 

### `npm:sass` dependencies 
[chokidar](https://www.npmjs.com/package/chokidar) [immutable](https://www.npmjs.com/package/immutable)  [source-map-js](https://www.npmjs.com/package/source-map-js)

### `npm:sass-embeded` dependencies

**1. [@bufbuild/protobuf](https://www.npmjs.com/package/%40bufbuild%2Fprotobuf)  
2.  [buffer-builder](https://www.npmjs.com/package/buffer-builder)    
3. [colorjs.io](https://www.npmjs.com/package/colorjs.io)    
4. [immutable](https://www.npmjs.com/package/immutable)   
5. [rxjs](https://www.npmjs.com/package/rxjs) 
6. [  supports-color](https://www.npmjs.com/package/supports-color)   
7. [sync-child-process](https://www.npmjs.com/package/sync-child-process)  
8.  [varint](https://www.npmjs.com/package/varint)**

So my questios is **whats makes `sass-embeded` to use more dependencies than `sass`**

**Comment by ntkme** [comment]
This is totally expected because they are implemented differently. `sass` package is running dart compiled JS, where `sass-embedded` runs pure dart as a child process and use JS wrapper code to communicate with dart. In summary, `sass`’s JS dependencies are implementing core functionalities, where in the `sass-embedded` these core functionalities are implemented in pure dart and compiled into a prebuilt dart snapshot so that you don’t see them listed as npm dependencies at all. OTOH, the wrapper needs lots of infrastructure code to communicate between Dart and JS, the dependencies for `sass-embedded` are either for the communication or for implementing the host side of JS API.
