### ISSUE TITLE
Undefined function math.div

### ISSUE THREAD

**Issue by claudia-romano** [sass/embedded-host-node#54]
Hi there, I'm using this as a replacement of the default sass compiler but I'm getting the undefined function error when using the div function:

```
Error: Undefined function.
12 │   width: math.div(floor(400% * math.div(100, 16)), 100);
```

I'm aware this is still a beta, so I was wondering if this has not been implemented yet or I'm doing something wrong on my side. Thanks.

**Comment by polarbirke** [comment]
Did you `@use "sass:math";` at the top of your file?

https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by claudia-romano** [comment]
I'm using the [npm module](https://www.npmjs.com/package/sass-embedded). It's 1.0.0-beta.1. Is there a different version? Thank you.

**Comment by stof** [comment]
Looking at the code of the npm module, it does not download the latest version of the embedded compiler, but a specific release (probably the latest release at the time the npm module was built). This means that it currently downloads 1.0.0-beta.7 of the compiler released in February (and so without `math.div`) and not the 1.0.0-beta.8 version released 3 weeks ago (see https://github.com/sass/dart-sass-embedded/releases).

@nex3 a new release of the npm package seems necessary (and maybe changing the way the compiler version is selected)

**Comment by claudia-romano** [comment]
Thanks for the info. Is the node module something you plan on keeping updated or is it better to include it in a different way? Thanks!

**Comment by megclaypool** [comment]
I'm following this with interest too... I ran into the same problem as @claudia-romano 😛  I work on a cross-platform team, so being able to add sass-embed to our package.json and then just `npm install` on everybody's local is pretty great 😀  I... actually have no idea what you've got to do on your end to update the npm package 😆 Is there an easy way to automate it, maybe a hook or something so when you push a new release to github it automatically lands on the npmjs site too? Otherwise, how would you recommend we include sass-embed in our project?

**Comment by Awjin** [comment]
Sorry for the delay folks. Please upgrade to `1.0.0-beta.3`, which was just released and uses the latest version of the compiler.

**Comment by claudia-romano** [comment]
Thank you!
