### ISSUE TITLE
Not able to install on Apple M1

### ISSUE THREAD

**Issue by claudia-romano** [sass/embedded-host-node#66]
Hi there, we have included `sass-emebedded` as npm module for our [CSS framework](https://www.npmjs.com/package/codyhouse-framework). Some of our users have been having issues installing it on an Apple M1 device.
```
npm ERR! path /Users/alen/Desktop/Newbie~og/node_modules/sass-embedded
npm ERR! command failed
npm ERR! command sh -c node ./download-compiler-for-end-user.js
npm ERR! /Users/alen/Desktop/Newbie~og/node_modules/sass-embedded/dist/tool/utils.js:39
npm ERR!             throw Error(`Architecure ${process.arch} is not supported.`);
npm ERR!             ^
npm ERR! 
npm ERR! Error: Architecure arm64 is not supported.
npm ERR!     at /Users/alen/Desktop/Newbie~og/node_modules/sass-embedded/dist/tool/utils.js:39:19
npm ERR!     at Object.<anonymous> (/Users/alen/Desktop/Newbie~og/node_modules/sass-embedded/dist/tool/utils.js:41:3)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:973:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:997:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/alen/Desktop/Newbie~og/node_modules/sass-embedded/download-compiler-for-end-user.js:9:29)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1108:14)
```

Replacing `sass-embedded` with `sass` fixes the problem. You can find some additional info in [this issue](https://github.com/CodyHouse/codyhouse-framework/issues/99) by @alenm.

Do you know if there's a way to fix this error? Thank you.

**Comment by alenm** [comment]
Here are steps to reproduce this error.  You would need an **Apple M1 computer.** and the following steps.

1. [Download Codyhouse framework](https://github.com/CodyHouse/codyhouse-framework.git)
2. Run `npm install`
3. You will run into this error

```
/sass-embedded/dist/tool/utils.js:39
npm ERR! throw Error(`Architecure ${process.arch} is not supported.`);
npm ERR! Error: Architecure arm64 is not supported.
```

4. Error is suggesting `sass-embedded` is not working because Apple M1 is not supported.

Spent time googling the issue and learned about the transition to `sass` and `dart-sass` and I don't particular understand it well, so I might be mis-informed in what I'm doing. But from what I gathered I did the following:

5. Change the `package.json`  by doing the following:
	- changed  `gulp-sass` from `4.0.2` to `5.0.0` 
	- added `"sass": "^1.42.1"` 

6. Changed one line in `gupfile.js` to now require `sass`

```var sass = require('gulp-sass')(require('sass'));```

7. Run `npm install` and now another **error**. Now the `sass-embedded` is missing `dart-sass-embedded ENOENT` 

```
Error: spawn /Users/alen/Desktop/codyhouse-framework-master/node_modules/sass-embedded/dist/lib/src/vendor/dart-sass-embedded/dart-sass-embedded ENOENT
```

8.  In order to fix this issue is to just remove `"sass-embedded": "^1.0.0-beta.3"` completely from the `package.json`. 
9.  Change the `gulpfile.js`  so that the sass.complier requires sass 

```
var sass = require('gulp-sass')(require('sass'));
sass.compiler = require('sass');
```

Re-run `npm install` and then `npm run gulp watch` and it works.

**Comment by Awjin** [comment]
Related issue: [compiling Dart Sass for M1](https://github.com/sass/dart-sass/issues/1125).

Currently Github Actions does not support compiling the Sass compiler for M1 Macs. We can work around this for now by allowing `arm64` users to download and run the `x64` binary (which will invoke the first-time transpilation cost on M1).

The true fix of creating native binaries for M1 is only possible once Github Actions supports it.

**Comment by Awjin** [comment]
Just published `1.0.0-beta.4`, which should fix the install.

**Comment by alenm** [comment]
I can confirm that if you download [codyhouse framework](https://www.npmjs.com/package/codyhouse-framework) and change the `package.json` entry `"sass-embedded": "^1.0.0-beta.3"` to `"sass-embedded": "^1.0.0-beta.4"` and run `npm install` it all works on an Apple M1 laptop. No errors. Thank you.

**Comment by claudia-romano** [comment]
Great! Thank you for your help!
